package main.managers;

public enum Choices {
    GET_ALL_TASKS, GET_ALL_EPICS, GET_ALL_SUBTASKS, GET_BY_ID_TASK, GET_BY_ID_EPIC, GET_BY_ID_SUBTASK, GET_HISTORY,
    GET_PRIORITIZED, CREATE_TASK, CREATE_EPIC, CREATE_SUBTASK, DELETE_TASKS, DELETE_EPICS, DELETE_SUBTASKS, UPDATE_TASK,
    UPDATE_EPIC, UPDATE_SUBTASK, DELETE_BY_ID_TASK, DELETE_BY_ID_EPIC, DELETE_BY_ID_SUBTASK, GET_EPICS_SUBTASKS, ERROR
}
